### ISSUE TITLE
Error running gulp for the first time

### ISSUE THREAD

**Issue by RonaldF** [ZeekInteractive/heisenberg#16]
I got the theme installed, ran npm install and everything installed correctly.

When I went to run gulp for the first time I got the following error

```
Error: File to import not found or unreadable:  ../../components/foundation/scss/foundation/functions
```

The import is located in the base/_base.scss file on line 2

**Comment by patrickodacre** [comment]
Did you run "bower install" ? 

You need to run that before gulp. Gulp tries to compile your sass files. The sass files import Foundation mixins, etc. The error tells you that Foundation isn't found, which means you probably didn't install Foundation via the "bower install" command.

Here's a suggested order when getting setup; in the command line type:

1) npm install
2) bower install
3) gulp

**Comment by RonaldF** [comment]
Thank you patrickodacre, but when I run bower install it says no bower.json present. I looked in the Heisenberg theme files and did not see a bower.json file in there

**Comment by RonaldF** [comment]
Looking through the stale branch of Heisenberg there is a bower.json file. It seems like it got deleted or made obsolete between then and the Default Branch.

**Comment by patrickodacre** [comment]
There you go )

The older manifest may mention Foundation 5, still. You'll just have to change that to version 6 and you should be good to go.

**Comment by jacobarriola** [comment]
Addressing this now guys. Forgot to remove an old import path from Foundation 5. Will push up in a few.

**Comment by RonaldF** [comment]
Patrick, thanks again. I used that file, but when trying to update to foundation vs 6.0.4 I get the following error.

<img width="577" alt="screen shot 2015-12-17 at 9 24 41 pm" src="https://cloud.githubusercontent.com/assets/13787573/11888594/bb4a2896-a504-11e5-89ea-3d8e4fab0487.png">

While the

**Comment by jacobarriola** [comment]
@RonaldF the latest code should help you now. Thanks for reporting!

**Comment by jacobarriola** [comment]
@patrickodacre thanks for the help. I'm not using Bower for Foundation 6 since it now supports npm. Thanks for the help!

**Comment by RonaldF** [comment]
Thanks, I updated to the new version

**Comment by patrickodacre** [comment]
@RonaldF Glad it's working now :)
@jacobarriola Very cool. I had no idea. I'll revisit this once I upgrade to 6 myself. Cheers!
