### ISSUE TITLE
Problem with top bar in heisenberg

### ISSUE THREAD

**Issue by benthien** [ZeekInteractive/heisenberg#29]
I have used the heisenberg starter theme in the past and really liked it. I recently installed the latest version from GitHub. I tried to modify it by adding a top bar to the file header.php. Instead of drop down menus on the top bar I got fully expanded lists. I am using wamp64 server on my Windows 10 PC. Here is the code I used

```
<div data-sticky-container>
 <div id="widemenu" class="top-bar" data-sticky data-options="marginTop:0;">
   <div class="top-bar-left">
     <ul class="menu dropdown" data-dropdown-menu data-close-on-click-inside="false">
       <li><a href="http://ladle/index.html">Home</a></li>
       <li><a href="#">About</a>
         <ul class="menu">
	         <li><a href="http://ladle/ministries.html">Ministries</a></li>
	         <li><a href="http://ladle/times.html">Times</a></li>
	         <li><a href="http://ladle/lhttp://ladle/ocation.html">Directions</a></li>
	         <li><a href="http://ladle/LadleHistory.html">History</a></li>
	         <li><a href="http://ladle/LadleStories.html">Stories</a></li>
         </ul>
       </li>
       <li><a href="volunteers.html">Volunteer</a></li>
       <li><a href="# ">Donate</a>
         <ul class="menu">
	         <li><a href="http://ladle/DonateMoney.html">Donate Money</a></li>
	         <li><a href="http://ladle/DonateGoods.html">Donate Goods</a></li>
         </ul>
       </li>
       <li class="active"><a href="http://localhost/ladleBlog/wp-content/themes/heisenberg">Blog</a></li>
       <li><a href="#">Contact</a>
         <ul class="menu">
	         <li><a href="http://ladle/Attn_Ladle.php">Contact Us</a></li>
	         <li><a href="http://ladle/Attn_Ladle1.php">Join Prayer Team</a></li>
         </ul>
       </li>
       <li>
         <a href="http://ladle/assets/zoom_search/search.php">Search</a>
       </li>
     </ul>
   </div>
 [</div>]
</div>

```
I am only using wordpress for the Blog. Everything else was built using the Zurb template and is working fine. . Any suggestions would be appreciated. The Blog using an old version of heisenberg  can be seen at [ladlefellowship.org/blog](url).

**Comment by jacobarriola** [comment]
Hi @benthien -

According to you markup, looks like you're trying to use Foundation's dropdown menu module.  Have you imported the associated JavaScript for that module?

In the theme, we have an [example of how to import a Foundation JS module](https://github.com/ZeekInteractive/heisenberg/blob/master/assets/js/modules/foundation.js), which highlights including the tabs module.

According to the [Foundation docs](https://foundation.zurb.com/sites/docs/dropdown-menu.html#javascript-reference), to use the drilldown menu you'll need to include drilldown module.

Your [foundation.js file](https://github.com/ZeekInteractive/heisenberg/blob/master/assets/js/modules/foundation.js) should be something like this:

```js
import { Foundation } from 'foundation-sites/js/foundation.core'
import { DropdownMenu } from 'foundation-sites/js/foundation.dropdownMenu'

function initFoundation() {
  // Include the Foundation Modules that we'll use in the app
  Foundation.plugin(DropdownMenu, 'DropdownMenu')

  // Add jQuery to Foundation
  Foundation.addToJquery(jQuery)

  // Kick off foundation
  jQuery(document).foundation()
}

export default initFoundation
```

Just remember to be sure and include this module in the `main.js` file https://github.com/ZeekInteractive/heisenberg/blob/master/assets/js/main.js#L2

**Comment by benthien** [comment]
I included the following code in assets/js/modules/foundation.js

 

import { Foundation } from 'foundation-sites/js/foundation.core'

import { DropdownMenu } from 'foundation-sites/js/foundation.dropdownmenu'

import { sticky } from 'foundation-sites/js/foundation.sticky'

 

function initFoundation() {

  // Include the Foundation Modules that we'll use in the app

  Foundation.plugin(DropdownMenu,'DropdownMenu')

  Foundation.plugin(sticky,'sticky')

 

  // Add jQuery to Foundation

  Foundation.addToJquery(jQuery)

 

  // Kick off foundation

  jQuery(document).foundation()

}

 

export default initFoundation

 

and nothing changed. I wasn’t sure what I needed to do to asset/js/main.js.  This is what it contains

 

import '../sass/app.scss'

import initFoundation from './modules/foundation'

 

// Start Foundation JS Modules

initFoundation()

 

George Benthien

**Comment by jacobarriola** [comment]
@benthien 

1. did you recompile the JS?

`npm run dev` => non-minified css and js files

OR

`npm run prod` => minified js and css files

2. If you did recompile, are you getting any error messages in the browser console?

**Comment by benthien** [comment]
npm run dev didn’t work, but both npm run prod and  npm run build worked. Thank you for your help.

 

George
