### ISSUE TITLE
Markdown in README.md

### ISSUE THREAD

**Issue by michaelbeil** [ZeekInteractive/heisenberg#4]
I'd be happy to convert the HTML to markdown for this file in PR #3.

**Comment by michaelbeil** [comment]
https://github.com/michaelbeil/heisenberg/commit/c6210ec987481614e9d2cdd2aff89a7330159cd3 resolves this.

**Comment by jacobarriola** [comment]
Resolved with #3.

**Comment by michaelbeil** [comment]
:+1:
