### ISSUE TITLE
errors running npm install

### ISSUE THREAD

**Issue by damott** [ZeekInteractive/heisenberg#8]
From within the theme folder at the command prompt, ran npm install and received the errors shown in the attached two screenshots:

It is beyond my knowledge to understand what these errors are, how they might impact the development and/or how to resolve. 

Any insight would be greatly appreciated.

Running windows 8.1.

![screenshot 8](https://cloud.githubusercontent.com/assets/3526889/9563413/d728a6c4-4e50-11e5-8683-bb21d18245c7.png)
![screenshot 9](https://cloud.githubusercontent.com/assets/3526889/9563412/d728283e-4e50-11e5-9ff0-15c7a6e54452.png)

**Comment by DArcMattr** [comment]
I haven't duplicated this error yet, but it looks like the root of the problem is Node.JS needs Python in order to install & compile a key module on Windows. 

The main culprit is `node-gyp`, whose documentation shows that it needs Python 2.7.X *and* Visual Studio to be installed: https://github.com/nodejs/node-gyp

**Comment by damott** [comment]
Hi David, 


Thank you for your response. 


Would you recommend that I proceed to install Python 2.7.X and Visual Studio or do you feel there is a better approach?









Sent from Surface





From: David Arceneaux
Sent: ‎Saturday‎, ‎August‎ ‎29‎, ‎2015 ‎2‎:‎52‎ ‎PM
To: ZeekInteractive/heisenberg
Cc: damott





I haven't duplicated this error yet, but it looks like the root of the problem is Node.JS needs Python in order to install & compile a key module on Windows. 

The main culprit is node-gyp, whose documentation shows that it needs Python 2.7.X and Visual Studio to be installed: https://github.com/nodejs/node-gyp

**Comment by DArcMattr** [comment]
I still have yet to get a test install going on Windows, but I'd think that going with what's documented for the node-gyp module is best. 

I will work with Jacob to update the README for this project.

**Comment by damott** [comment]
Thank you David. 









Sent from Surface





From: David Arceneaux
Sent: ‎Friday‎, ‎September‎ ‎4‎, ‎2015 ‎12‎:‎21‎ ‎PM
To: ZeekInteractive/heisenberg
Cc: damott





I still have yet to get a test install going on Windows, but I'd think that going with what's documented for the node-gyp module is best. 

I will work with Jacob to update the README for this project.
